CREATE TABLE IF NOT EXISTS event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(255) NOT NULL,
    case_type VARCHAR(255),
    amount NUMERIC(38,2),
    currency VARCHAR(255),
    timestamp TIMESTAMP WITH TIME ZONE,
    CONSTRAINT uk_event_event_id UNIQUE (event_id)
);

CREATE TABLE IF NOT EXISTS event_signals (
    event_id BIGINT NOT NULL,
    signal VARCHAR(255),
    CONSTRAINT fk_event_signals_event FOREIGN KEY (event_id) REFERENCES event(id)
);

CREATE TABLE IF NOT EXISTS audit_record (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(50) NOT NULL,
    case_type VARCHAR(30),
    amount DECIMAL(10,2),
    currency VARCHAR(5),
    timestamp TIMESTAMP,
    is_at_risk BOOLEAN,
    risk_amount DECIMAL(10,2),
    root_cause VARCHAR(50),
    classification_confidence DECIMAL(4,3),
    signals_used TEXT,
    policy_rule_matched VARCHAR(200),
    action_taken VARCHAR(50),
    attempt_number INT,
    max_attempts_allowed INT,
    outcome VARCHAR(30),
    recovered_amount DECIMAL(10,2),
    stop_or_escalate_reason VARCHAR(200),
    lifecycle_state VARCHAR(50),
    next_eligible_action_at TIMESTAMP,
    recovery_window_expires_at TIMESTAMP
);

ALTER TABLE audit_record ADD COLUMN IF NOT EXISTS customer_ref VARCHAR(120);
ALTER TABLE audit_record ADD COLUMN IF NOT EXISTS source VARCHAR(30);
ALTER TABLE audit_record ADD COLUMN IF NOT EXISTS verification_result VARCHAR(50);
ALTER TABLE audit_record ADD COLUMN IF NOT EXISTS detail TEXT;
ALTER TABLE audit_record ADD COLUMN IF NOT EXISTS gateway_error_reason VARCHAR(100);
ALTER TABLE audit_record ADD COLUMN IF NOT EXISTS gateway_order_id VARCHAR(50);
ALTER TABLE audit_record ADD COLUMN IF NOT EXISTS gateway_payment_id VARCHAR(50);
ALTER TABLE audit_record ADD COLUMN IF NOT EXISTS escalation_reason VARCHAR(100);
CREATE UNIQUE INDEX IF NOT EXISTS uk_audit_record_event_id ON audit_record(event_id);
CREATE UNIQUE INDEX IF NOT EXISTS uk_audit_record_gateway_order ON audit_record(gateway_order_id);

CREATE TABLE IF NOT EXISTS audit_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(50) NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    previous_state VARCHAR(50),
    new_state VARCHAR(50) NOT NULL,
    root_cause VARCHAR(50),
    classification_confidence DECIMAL(4,3),
    policy_rule_matched VARCHAR(200),
    action_taken VARCHAR(50),
    attempt_number INT,
    max_attempts_allowed INT,
    outcome_if_terminal VARCHAR(30),
    reason VARCHAR(500),
    actor VARCHAR(30) NOT NULL,
    idempotency_key VARCHAR(150) NOT NULL,
    CONSTRAINT uk_audit_history_idempotency UNIQUE (idempotency_key)
);
CREATE INDEX IF NOT EXISTS idx_history_event_id ON audit_history(event_id);

CREATE TABLE IF NOT EXISTS razorpay_test_order (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    internal_request_id VARCHAR(40) NOT NULL UNIQUE,
    razorpay_order_id VARCHAR(50) NOT NULL UNIQUE,
    receipt VARCHAR(40) NOT NULL UNIQUE,
    amount_inr DECIMAL(12,2) NOT NULL,
    amount_paise BIGINT NOT NULL,
    currency VARCHAR(3) NOT NULL,
    status VARCHAR(40) NOT NULL,
    mode VARCHAR(10) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS razorpay_test_checkout_attempt (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    internal_request_id VARCHAR(40) NOT NULL,
    razorpay_order_id VARCHAR(50) NOT NULL,
    razorpay_payment_id VARCHAR(50),
    razorpay_signature VARCHAR(512),
    event_type VARCHAR(40) NOT NULL,
    reason VARCHAR(100),
    status VARCHAR(40) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    verified_at TIMESTAMP,
    verification_failure_code VARCHAR(50),
    CONSTRAINT uk_test_checkout_order_payment UNIQUE (razorpay_order_id, razorpay_payment_id)
);

ALTER TABLE razorpay_test_checkout_attempt ADD COLUMN IF NOT EXISTS error_code VARCHAR(100);
ALTER TABLE razorpay_test_checkout_attempt ADD COLUMN IF NOT EXISTS error_description VARCHAR(500);
ALTER TABLE razorpay_test_checkout_attempt ADD COLUMN IF NOT EXISTS error_source VARCHAR(100);
ALTER TABLE razorpay_test_checkout_attempt ADD COLUMN IF NOT EXISTS error_step VARCHAR(100);
ALTER TABLE razorpay_test_checkout_attempt ADD COLUMN IF NOT EXISTS customer_ref VARCHAR(120);
ALTER TABLE razorpay_test_checkout_attempt ADD COLUMN IF NOT EXISTS latency_ms BIGINT;

CREATE TABLE IF NOT EXISTS agent_decision_trace (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(50) NOT NULL,
    stage VARCHAR(30) NOT NULL,
    summary VARCHAR(200) NOT NULL,
    detail TEXT,
    actor VARCHAR(40) NOT NULL,
    timestamp TIMESTAMP NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_agent_trace_event ON agent_decision_trace(event_id);

CREATE TABLE IF NOT EXISTS payment_reservation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id VARCHAR(50) NOT NULL UNIQUE,
    event_id VARCHAR(50) NOT NULL,
    idempotency_key VARCHAR(100) NOT NULL UNIQUE,
    order_id VARCHAR(50) NOT NULL,
    amount DECIMAL(12,2) NOT NULL,
    customer_ref VARCHAR(120),
    created_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    status VARCHAR(40) NOT NULL,
    fallback_attempts INT NOT NULL,
    max_fallback_attempts INT NOT NULL
);

CREATE TABLE IF NOT EXISTS recovery_demo_case (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(50) NOT NULL UNIQUE,
    case_type VARCHAR(30) NOT NULL,
    root_cause VARCHAR(50) NOT NULL,
    amount DECIMAL(12,2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    policy_action VARCHAR(50) NOT NULL,
    outcome VARCHAR(30) NOT NULL,
    recovery_status VARCHAR(50) NOT NULL,
    demo_only BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    recovered_at TIMESTAMP,
    version BIGINT,
    CONSTRAINT uk_recovery_demo_event_id UNIQUE (event_id)
);

CREATE TABLE IF NOT EXISTS recovery_payment_link (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recovery_event_id VARCHAR(50) NOT NULL UNIQUE,
    internal_request_id VARCHAR(40) NOT NULL UNIQUE,
    razorpay_order_id VARCHAR(50) NOT NULL UNIQUE,
    razorpay_payment_id VARCHAR(50) UNIQUE,
    amount_inr DECIMAL(12,2) NOT NULL,
    amount_paise BIGINT NOT NULL,
    currency VARCHAR(3) NOT NULL,
    mode VARCHAR(10) NOT NULL,
    purpose VARCHAR(30) NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    verified_at TIMESTAMP,
    recovered_at TIMESTAMP,
    CONSTRAINT fk_recovery_link_case FOREIGN KEY (recovery_event_id) REFERENCES recovery_demo_case(event_id)
);

CREATE TABLE IF NOT EXISTS transaction_recovery_payment_link (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(255) NOT NULL UNIQUE,
    internal_request_id VARCHAR(40) NOT NULL UNIQUE,
    razorpay_order_id VARCHAR(50) NOT NULL UNIQUE,
    razorpay_payment_id VARCHAR(50) UNIQUE,
    amount_inr DECIMAL(12,2) NOT NULL,
    amount_paise BIGINT NOT NULL,
    currency VARCHAR(3) NOT NULL,
    mode VARCHAR(10) NOT NULL,
    purpose VARCHAR(40) NOT NULL,
    recovery_action ENUM('RESUME_PAYMENT','CHOOSE_ANOTHER_PAYMENT_METHOD','TRY_PAYMENT_AGAIN_SECURELY','TRY_PAYMENT_AGAIN','PAY_MANUALLY') NOT NULL,
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    verified_at TIMESTAMP,
    recovered_at TIMESTAMP,
    version BIGINT,
    CONSTRAINT fk_txn_recovery_link_event FOREIGN KEY (event_id) REFERENCES event(event_id)
);

-- Remove Hibernate-generated legacy checks whose allowed values became stale.
ALTER TABLE audit_history DROP CONSTRAINT IF EXISTS CONSTRAINT_E8;
ALTER TABLE audit_history DROP CONSTRAINT IF EXISTS CONSTRAINT_E80;
ALTER TABLE audit_history DROP CONSTRAINT IF EXISTS CONSTRAINT_E800C;
ALTER TABLE audit_record DROP CONSTRAINT IF EXISTS CONSTRAINT_D6;

ALTER TABLE audit_history ADD CONSTRAINT IF NOT EXISTS ck_audit_history_action_taken CHECK (action_taken IN ('RETRY_PAYMENT','VERIFY_STATUS','SEND_ALT_PAYMENT_LINK','SEND_RECOVERY_LINK','NO_ACTION_STOP','ESCALATE_MERCHANT','SCHEDULE_MANDATE_RETRY'));
ALTER TABLE audit_history DROP CONSTRAINT IF EXISTS ck_audit_history_actor;
ALTER TABLE audit_history ADD CONSTRAINT ck_audit_history_actor CHECK (actor IN ('SYSTEM_SIMULATION','MERCHANT_MANUAL','RAZORPAY_TEST_VERIFICATION','RESERVATION_SYSTEM'));
ALTER TABLE audit_history ADD CONSTRAINT IF NOT EXISTS ck_audit_history_new_state CHECK (new_state IN ('RECEIVED','AT_RISK','CLASSIFIED','ACTION_APPROVED','RETRY_SCHEDULED','VERIFYING_PAYMENT','RECOVERY_LINK_SENT','RETRY_EXHAUSTED','RECOVERED','RECOVERED_BY_VERIFIED_TEST_PAYMENT','NOT_RECOVERED','STOPPED','ESCALATED'));
ALTER TABLE audit_history ADD CONSTRAINT IF NOT EXISTS ck_audit_history_outcome CHECK (outcome_if_terminal IN ('RECOVERED','NOT_RECOVERED','ESCALATED','STOPPED_CORRECTLY'));
ALTER TABLE audit_history ADD CONSTRAINT IF NOT EXISTS ck_audit_history_previous_state CHECK (previous_state IN ('RECEIVED','AT_RISK','CLASSIFIED','ACTION_APPROVED','RETRY_SCHEDULED','VERIFYING_PAYMENT','RECOVERY_LINK_SENT','RETRY_EXHAUSTED','RECOVERED','RECOVERED_BY_VERIFIED_TEST_PAYMENT','NOT_RECOVERED','STOPPED','ESCALATED'));
ALTER TABLE audit_history ADD CONSTRAINT IF NOT EXISTS ck_audit_history_root_cause CHECK (root_cause IN ('BANK_TEMP_ERROR','WEAK_NETWORK','PAYMENT_PENDING','INSUFFICIENT_BALANCE','USER_CANCELLED','INCORRECT_PIN','MERCHANT_GATEWAY_ISSUE','CHECKOUT_ABANDONED','MANDATE_FAILED_RETRYABLE','MANDATE_EXPIRED','UNKNOWN'));
ALTER TABLE audit_record ADD CONSTRAINT IF NOT EXISTS ck_audit_record_lifecycle_state CHECK (lifecycle_state IN ('RECEIVED','AT_RISK','CLASSIFIED','ACTION_APPROVED','RETRY_SCHEDULED','VERIFYING_PAYMENT','RECOVERY_LINK_SENT','RETRY_EXHAUSTED','RECOVERED','RECOVERED_BY_VERIFIED_TEST_PAYMENT','NOT_RECOVERED','STOPPED','ESCALATED'));
ALTER TABLE recovery_demo_case ADD CONSTRAINT IF NOT EXISTS ck_recovery_demo_outcome CHECK (outcome IN ('RECOVERED','NOT_RECOVERED','ESCALATED','STOPPED_CORRECTLY'));
ALTER TABLE recovery_demo_case ADD CONSTRAINT IF NOT EXISTS ck_recovery_demo_policy_action CHECK (policy_action IN ('RETRY_PAYMENT','VERIFY_STATUS','SEND_ALT_PAYMENT_LINK','SEND_RECOVERY_LINK','NO_ACTION_STOP','ESCALATE_MERCHANT','SCHEDULE_MANDATE_RETRY'));
ALTER TABLE recovery_demo_case ADD CONSTRAINT IF NOT EXISTS ck_recovery_demo_root_cause CHECK (root_cause IN ('BANK_TEMP_ERROR','WEAK_NETWORK','PAYMENT_PENDING','INSUFFICIENT_BALANCE','USER_CANCELLED','INCORRECT_PIN','MERCHANT_GATEWAY_ISSUE','CHECKOUT_ABANDONED','MANDATE_FAILED_RETRYABLE','MANDATE_EXPIRED','UNKNOWN'));
